---

- hosts: nodes
  vars:
    user1: Deepankar
    user2: Chetan
    user3: Capgemini
  tasks:
    
   - name: Create a user named {{user1}},{{user2}},{{user3}}
     user:
       name: "{{item}}"
       state: present
     with_items:
        - "{{user1}}"
        - "{{user2}}"
        - "{{user3}}"
