---

- hosts: nodes
  tasks:
    - name: install nginx
      package:
         name: nginx
         state: present
   
    - name: update nginx
      copy:
         src: /home/ubuntu/default
         dest: /etc/nginx/sites-available/default

  handlers:
    - name: restart nginx
      service:
         name: nginx
         state: restarted
    
