---

- hosts: nodes
  tasks:
    - name: copy
      copy:
        src: template.j2
        dest: /home/ubuntu/copy_module
    - name: template
      template:
        src: template.j2
        dest: /home/ubuntu/template_module
