---

- hosts: nodes
  tasks:
    - name: install apache2
      package:
         name: apache2
         state: present
    - name: Starting service
      service:
         name: apache2
         state: started
    - name: updating index file
      copy:
        content: "<h1> Welcome to devops training </h1>"
        dest: /var/www/html/index.html
